yazilar:
  sebep: 'Yok'
  yetkiyok: '§cGerekli yetkiye sahip değilsin!'
  komuthatirlatma: '§b/§6ug §e{0} §e{1} §7(§csn§b,§cdk§b,§csa§b,§cgün§7) §b<§esebep§b>'
  komut-oyuncu-0-yerine: '§b<§eoyuncu§b>'
  komut-sure-1-yerine: '§b<§esüre§b>'
  yasak-kaldirildi: '§b{0} §eadlı oyuncunun yasağı kaldırıldı.'
  yasak-yok: '§b{0} §eadlı oyuncu yasaklanmamamış.'
  yasaklandi: '§b{0} §eadlı oyuncu sunucudan yasaklandı.'
  dis-yasaklandi: '§b{0} §eadlı çevrimdışı oyuncu§7(hatalara sebep olabilir) §esunucudan yasaklandı.'
  sayi-hatali: '§cLütfen geçerli bir sayı giriniz!'
  tip-hatali: '§eLüfen geçerli bir süre tipi giriniz!'
  yasak-mesaj:
  - '§6§l|----------------------------------------|'
  - '§c§lSUNUCUDAN GEÇİCİ OLARAK UZAKLAŞTIRILDIN.'
  - '§e{0}'
  - ' '
  - ' '
  - '§6§lSebep'
  - '§f{1}'
  - ' '
  - '§fEğer bunun yanlış olduğunu düşünüyorsan'
  - '§abizimle iletişime geç.'
  - ' '
  - '§3Site: §fwww.fahrenium.com'
  - '§3Discord: §fdiscord.fahrenium.com'
  - '§6§l|------------------------|'
  ugc: '§b/§6ugc §b<§ereload§7|§erestart§7|§eplugin§b>'
  ugc-reload: '§eAyar dosyası yeniden yüklendi.'
  ugc-restart: '§eAyar dosyası §csıfırlandı§e.'
  ugc-plugin: '§eEklenti tekrar §ayüklendi'